OrdererOrgs:
    - Name: Orderer
      Domain: vtan.com
      EnableNodeOUs: true
      Specs:
          - Hostname: orderer

PeerOrgs:
    - Name: Citizen
      Domain: citizen.vtan.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: RTO
      Domain: rto.vtan.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: Pollution
      Domain: pollution.vtan.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: Insurance
      Domain: insurance.vtan.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: Police
      Domain: police.vtan.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1
