OrdererOrgs:
    - Name: Orderer
      Domain: vehicle.com
      EnableNodeOUs: true
      Specs:
          - Hostname: orderer

PeerOrgs:
    - Name: Citizen
      Domain: citizen.vehicle.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: RTO
      Domain: rto.vehicle.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: Pollution
      Domain: pollution.vehicle.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: Insurance
      Domain: insurance.vehicle.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: Police
      Domain: police.vehicle.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1
