version: "2"

volumes:
    orderer.vtan.com:
    peer0.citizen.vtan.com:
    peer0.rto.vtan.com:
    peer0.pollution.vtan.com:
    peer0.insurance.vtan.com:
    peer0.police.vtan.com:
    caCitizen:
    caRTO:
    caPollution:
    caInsurance:
    caPolice:

networks:
    vtannet:

services:
    orderer.vtan.com:
        extends:
            file: base/docker-compose-base.yaml
            service: orderer.vtan.com
        container_name: orderer.vtan.com
        networks:
            - vtannet

    peer0.citizen.vtan.com:
        container_name: peer0.citizen.vtan.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer0.citizen.vtan.com
        networks:
            - vtannet
        depends_on:
            - couchdb.peer0.citizen.vtan.com

    peer0.rto.vtan.com:
        container_name: peer0.rto.vtan.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer0.rto.vtan.com
        networks:
            - vtannet
        depends_on:
            - couchdb.peer0.rto.vtan.com

    peer0.pollution.vtan.com:
        container_name: peer0.pollution.vtan.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer0.pollution.vtan.com
        networks:
            - vtannet
        depends_on:
            - couchdb.peer0.pollution.vtan.com

    peer0.insurance.vtan.com:
        container_name: peer0.insurance.vtan.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer0.insurance.vtan.com
        networks:
            - vtannet
        depends_on:
            - couchdb.peer0.insurance.vtan.com

    peer0.police.vtan.com:
        container_name: peer0.police.vtan.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer0.police.vtan.com
        networks:
            - vtannet
        depends_on:
            - couchdb.peer0.police.vtan.com

    caCitizen:
        container_name: caCitizen
        extends:
            file: base/docker-compose-base.yaml
            service: caCitizen
        networks:
            - vtannet

    caRTO:
        container_name: caRTO
        extends:
            file: base/docker-compose-base.yaml
            service: caRTO
        networks:
            - vtannet

    caPollution:
        container_name: caPollution
        extends:
            file: base/docker-compose-base.yaml
            service: caPollution
        networks:
            - vtannet

    caInsurance:
        container_name: caInsurance
        extends:
            file: base/docker-compose-base.yaml
            service: caInsurance
        networks:
            - vtannet

    caPolice:
        container_name: caPolice
        extends:
            file: base/docker-compose-base.yaml
            service: caPolice
        networks:
            - vtannet

    couchdb.peer0.citizen.vtan.com:
        container_name: couchdb.peer0.citizen.vtan.com
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        ports:
            - "5984:5984"
        networks:
            - vtannet

    couchdb.peer0.rto.vtan.com:
        container_name: couchdb.peer0.rto.vtan.com
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        ports:
            - "6984:5984"
        networks:
            - vtannet

    couchdb.peer0.pollution.vtan.com:
        container_name: couchdb.peer0.pollution.vtan.com
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        ports:
            - "7984:5984"
        networks:
            - vtannet

    couchdb.peer0.insurance.vtan.com:
        container_name: couchdb.peer0.insurance.vtan.com
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        ports:
            - "8984:5984"
        networks:
            - vtannet

    couchdb.peer0.police.vtan.com:
        container_name: couchdb.peer0.police.vtan.com
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        ports:
            - "9984:5984"
        networks:
            - vtannet

    cli:
        container_name: cli
        image: hyperledger/fabric-tools:$IMAGE_TAG
        tty: true
        stdin_open: true
        environment:
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            #- FABRIC_LOGGING_SPEC=DEBUG
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=peer0.citizen.vtan.com:7051
            - CORE_PEER_LOCALMSPID=CitizenMSP
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/citizen.vtan.com/peers/peer0.citizen.vtan.com/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/citizen.vtan.com/peers/peer0.citizen.vtan.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/citizen.vtan.com/peers/peer0.citizen.vtan.com/tls/ca.crt
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/citizen.vtan.com/users/Admin@citizen.vtan.com/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ./../chaincode/:/opt/gopath/src/
            - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
            - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        depends_on:
            - orderer.vtan.com
            - peer0.citizen.vtan.com
            - peer0.rto.vtan.com
            - peer0.pollution.vtan.com
            - peer0.insurance.vtan.com
            - peer0.police.vtan.com
            - caCitizen
            - caRTO
            - caPollution
            - caInsurance
            - caPolice
        networks:
            - vtannet
