---
Organizations:
    - &OrdererOrg
      Name: OrdererOrg
      ID: OrdererMSP
      MSPDir: crypto-config/ordererOrganizations/vehicle.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('OrdererMSP.admin')"

    - &Citizen
      Name: CitizenMSP
      ID: CitizenMSP
      MSPDir: crypto-config/peerOrganizations/citizen.vehicle.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('CitizenMSP.admin', 'CitizenMSP.peer', 'CitizenMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('CitizenMSP.admin', 'CitizenMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('CitizenMSP.admin')"

    - &RTO
      Name: RTOMSP
      ID: RTOMSP
      MSPDir: crypto-config/peerOrganizations/rto.vehicle.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('RTOMSP.admin', 'RTOMSP.peer', 'RTOMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('RTOMSP.admin', 'RTOMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('RTOMSP.admin')"

    - &Pollution
      Name: PollutionMSP
      ID: PollutionMSP
      MSPDir: crypto-config/peerOrganizations/pollution.vehicle.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('PollutionMSP.admin', 'PollutionMSP.peer', 'PollutionMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('PollutionMSP.admin', 'PollutionMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('PollutionMSP.admin')"

    - &Insurance
      Name: InsuranceMSP
      ID: InsuranceMSP
      MSPDir: crypto-config/peerOrganizations/insurance.vehicle.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('InsuranceMSP.admin', 'InsuranceMSP.peer', 'InsuranceMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('InsuranceMSP.admin', 'InsuranceMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('InsuranceMSP.admin')"

    - &Police
      Name: PoliceMSP
      ID: PoliceMSP
      MSPDir: crypto-config/peerOrganizations/police.vehicle.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('PoliceMSP.admin', 'PoliceMSP.peer', 'PoliceMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('PoliceMSP.admin', 'PoliceMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('PoliceMSP.admin')"

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.vehicle.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    LawNetOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Citizen
                    - *RTO
                    - *Pollution
                    - *Insurance
                    - *Police
    LawNetChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Citizen
                - *RTO
                - *Pollution
                - *Insurance
                - *Police
            Capabilities:
                <<: *ApplicationCapabilities
